site_name: 13Repository | 8ARMS

theme:
  name: material
  language: zh-TW
  icon:
    logo: material/quadcopter
  features:
    - search.highlight #搜尋結果高亮顯示
    - navigation.top #回到頂部按鍵
    - navigation.tabs #導覽列
    - navigation.tabs.sticky #導覽列黏性
    - navigation.path #路徑顯示
  palette:
    scheme: slate #深色模式
    primary: black #標題、側邊欄、文本鏈接顏色
    accent: yellow

copyright: Copyright @ 2019-2026 13Repository All Rights Reserved
