site_name: 13Repository | 8ARMS
site_url: https://8armsnet.github.io/
site_author: 8arms.net

theme:
  name: material
  language: zh-TW
  icon:
    logo: material/quadcopter

  features:
    - search.highlight #搜尋結果高亮顯示
    - navigation.top #回到頂部按鍵
    - navigation.tabs #導覽列
    - navigation.tabs.sticky #導覽列黏性
    - navigation.path #路徑顯示

  palette:
    scheme: slate #深色模式
    primary: black #標題、側邊欄、文本鏈接顏色
    accent: yellow

extra_css:
  - stylesheets/extra.css

copyright: Copyright @ 2019-2026 13Repository All Rights Reserved

nav:
  - 首頁: index.md
  - 載具零組件:
    - FC 飛控: 載具零組件\FC飛控.md #A0-5-1
    - ESC 電子調速器: 載具零組件\ESC電子調速器.md #A0-4-1
    - Motor 馬達: 載具零組件\Motor馬達.md #A0-3-1
    - Prop 槳葉: 載具零組件\Prop槳葉.md #A0-3-2
  - 衛星接收器:
    - GNSS 接收器: GNSS衛星接收器\GNSS接收器.md #A0-3-3
    - GNSS 模組: GNSS衛星接收器\GNSS模組.md #A0-3-4
  - 電池組:
    - 電池組/查看說明.md
    - 1S 電池組: 電池組\1S電池組.md #A0-5-6
    - 3S 電池組: 電池組\3S電池組.md #A0-4-6
    - 4S 電池組: 電池組\4S電池組.md #A0-3-6
    - 6S 電池組: 電池組\6S電池組.md #A0-2-6
    - 12S 電池組: 電池組\12S電池組.md #A0-1-6
    - 固態電池 300wh-kg: 電池組\固態電池300wh-kg.md #A0-5-7
    - 固態電池 350wh-kg: 電池組\固態電池350wh-kg.md #A0-4-7
    - 固態電池 400wh-kg: 電池組\固態電池400wh-kg.md #A0-3-7
    - 固態電池 520wh-kg: 電池組\固態電池520wh-kg.md #A0-2-7
    - 固態電池 600wh-kg: 電池組\固態電池600wh-kg.md #A0-1-7
  - 傳輸模組:
    - TELE 數傳模組: 傳輸模組\TELE數傳模組.md #A0-2-4
    - VTX/RX 圖傳模組: 傳輸模組\VTX-RX圖傳模組.md #A0-2-5
    - CTX/RX 控制模組: 傳輸模組\CTX-RX控制模組.md #A0-3-5
  - 耗材:
    - 接頭: 耗材/接頭.md #A0-4-2
    - 線材: 耗材/AWG線材.md #A0-4-3
    - 機架: 耗材/Frame機架.md #A0-4-4
  - 工具設備: 工具設備/index.md #A0-4-5
  - 學習套件:
    - WB330 多旋翼套件: 學習套件/WB330多旋翼套件.md #A0-2-1
    - WB450 多旋翼套件: 學習套件/WB450多旋翼套件.md #A0-2-2
    - WB550 多旋翼套件: 學習套件/WB550多旋翼套件.md #A0-2-3
  - 成品機型:
    - 鐵頭系列: 成品機型/鐵頭系列.md #A0-1-1
    - 方舟系列: 成品機型/方舟系列.md #A0-1-2
    - 奈我何系列: 成品機型/奈我何系列.md #A0-1-3
    - 梅杜莎系列: 成品機型/梅杜莎系列.md #A0-1-4
    - 修羅系列: 成品機型/修羅系列.md #A0-1-5
